### ISSUE TITLE
`date-format` used in OpenAPI Spec is not high enough resolution

### ISSUE THREAD

**Issue by madpah** [CycloneDX/transparency-exchange-api#178]
`createdBy` is used for sorting, but the format specified is:

```
    date-time:
      type: string
      description: Timestamp
      format: date-time
      pattern: "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$"
      example: '2024-03-20T15:30:00Z'
```

This has a resolution of seconds. Multiple releases are definitely possible in a single second - so this would mean ordering is not accurate in all scenarios.

FYI @nscuro @oej
